apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deluge
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
      - name: deluge
        image: lsioarmhf/deluge
        ports:
        - containerPort: 8112
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: default
spec:
  ports:
  - port: 8112
  selector:
    app: deluge
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deluge
  namespace: default
spec:
  rules:
  - host: deluge.cluster
    http:
      paths:
      - backend:
          serviceName: deluge
          servicePort: 8112
